name: .NET Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Backend/Csandun.TaskManagerApi

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Backend/Csandun.TaskManagerApi

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Backend/Csandun.TaskManagerApi
